---
abstract: 'An Object Relational Mapper (ORM) for the Amazon SimpleDB service.'
author:
  - 'JT Smith <RIZEN@cpan.org>'
generated_by: 'Dist::Zilla version 1.093400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SimpleDB-Class
requires:
  AnyEvent::HTTP: 1.44
  DateTime: 0
  DateTime::Format::Strptime: 0
  Digest::SHA: 0
  Exception::Class: 0
  Memcached::libmemcached: 0.3102
  Module::Find: 0
  Moose: 0
  MooseX::ClassAttribute: 0
  Net::SSLeay: 1.35
  Test::Deep: 0
  Test::More: 0
  URI: 0
  UUID::Tiny: 0
  XML::Simple: 0
version: 0.0201
